feat(scripts): Add create local database
dataforgoodfr/CarbonBombs pull request #152
Opened 2023-10-28 11:39 UTC by Baboo7

2023-10-29 10:20 UTC, Nathanlauga requested changes
Need to put the database file name into conf.py
Also do we need to push this file into the repo ? if not then we should put it into .gitignore

2023-10-29 10:20 UTC, Nathanlauga commented on carbon_bombs/io/neo4j.py
> +    with open('database.json', 'w') as convert_file:
Put the file name in `conf.py`
Also maybe use : the following path `{DATA_NEO4J_PATH}/database.json`

2023-10-30 09:02 UTC, Baboo7 commented
@Nathanlauga it's updated!

2023-10-30 15:53 UTC, Nathanlauga approved these changes
Ok!

2023-10-30 15:55 UTC, merged