7-refactor-of-dictionary-folder
dataforgoodfr/CarbonBombs pull request #20
Opened 2023-06-07 13:04 UTC by gpenessot

- moved manual_match.py and uniform_company_name.py from root folder to `data_sources` 
- changed imports in scrapper.py, connexion.py, carbon_bomb.py

2023-06-08 15:39 UTC, mnicolleUTC requested changes

2023-06-08 21:18 UTC, gpenessot commented on connexion.py
>      file_path = './uniform_company_name.py'
ok

2023-06-08 21:35 UTC, gpenessot commented
@mnicolleUTC file connexion.py updated after your review :)

2023-06-09 07:18 UTC, mnicolleUTC approved these changes

2023-06-09 07:29 UTC, merged